"""Track 3 support: analyst investigation / case view for the v1 stateless detector + cascade.

This is explicitly a SUPPORTING layer on top of the declared primary track
(Track 1 -- Detection & Alert Prioritization; see report/TECHNICAL_REPORT.md §1).
It does not re-run its own detector evaluation or add a separate baseline; it
surfaces evidence and explanations for the already-evaluated Stage 1 (v1) /
Stage 2 cascade (src/models/cascade.py, src/models/stateless_model.py). Per the
brief: "a polished dashboard without validated detection evidence is not
sufficient" -- every number shown here reads from results/metrics/*.json,
generated by the evaluation pipeline, not computed ad hoc in the UI.

Uses v1 (base 14 features) throughout -- the v2 session-repeat model was
rejected after failing a mixed-session stress test (see report §9). Never
point this at models/stateless_lgbm_v2_rejected.pkl (retained as evidence only).

Safety: advisory only. No button here blocks DNS, quarantines a host, or
modifies any live system -- this mirrors the project's own security constraint
(detection outputs are advisory; human approval required for any response).
"""
import sys
import json
from pathlib import Path

import numpy as np
import pandas as pd
import streamlit as st

project_root = Path(__file__).resolve().parent.parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

from src.data.load import load_split
from src.explain.shap_explain import load_bundle, build_explainer, local_explanation
from src.features.stateful_context import build_stateful_context
from src.models.cascade import _token_from_capture_file

st.set_page_config(page_title="DNS Exfiltration Analyst Case View", layout="wide")


@st.cache_resource
def get_model_and_explainer():
    model, features = load_bundle()  # defaults to models/stateless_lgbm_v1.pkl
    explainer = build_explainer(model)
    return model, features, explainer


@st.cache_data
def get_threshold_record():
    """Single source of truth for the live operating point. Every displayed FPR/threshold
    string is derived from this file -- nothing about the operating point is hardcoded in
    the UI, so the product cannot silently diverge from the report."""
    return json.load(open("models/stateless_threshold_v1.json"))


@st.cache_data
def get_test_data():
    test = load_split("test")
    threshold = get_threshold_record()["threshold"]
    model, features, _ = get_model_and_explainer()
    test = test.copy()
    test["raw_score"] = model.predict_proba(test[features])[:, 1]
    test["base_trace"] = test["session_id"].apply(lambda s: _token_from_capture_file(s.split("::")[0]))
    return test, threshold


@st.cache_data
def get_cascade_report():
    return json.load(open("results/metrics/cascade_report.json"))


@st.cache_data
def get_ranking_quality():
    path = Path("results/metrics/ranking_quality_v1.json")
    return json.load(open(path)) if path.exists() else None


@st.cache_data
def get_shap_global():
    path = Path("results/metrics/shap_global_summary.json")
    if path.exists():
        return json.load(open(path))
    return None


@st.cache_data
def get_model_metrics():
    stateless = json.load(open("results/metrics/stateless_model_v1_report.json"))
    loto = json.load(open("results/metrics/leave_one_day_out_report.json"))
    return stateless, loto


def decision_band(score: float, threshold: float) -> tuple:
    if score >= threshold:
        return "ALERT", "#c0392b"
    if score >= 0.4:
        return "SUSPICIOUS", "#e67e22"
    return "BENIGN", "#27ae60"


def verdict_badge(session_verdict: str) -> tuple:
    labels = {
        "not_escalated": ("Stage 1 only — not escalated", "#27ae60"),
        "escalated_confirmed_alert": ("Escalated + Stage 2 confirmed", "#c0392b"),
        "escalated_unconfirmed_human_review": ("Escalated — unconfirmed, human review needed", "#e67e22"),
        "escalated_context_unavailable_fallback_stage1": ("Escalated — stateful context unavailable, Stage 1 verdict stands", "#7f8c8d"),
    }
    return labels.get(session_verdict, (session_verdict, "#7f8c8d"))


st.title("DNS Exfiltration & Tunnelling — Analyst Case View")
st.caption(
    "Track 1 (Detection & Alert Prioritization) primary submission — this view is a supporting "
    "Track 3 (Analyst Investigation & Explanation) layer over the evaluated v1 detector and "
    "cascade (Track 2 kept as a supporting interpretability layer, not a cost optimization; "
    "see report/TECHNICAL_REPORT.md §1). Advisory only: nothing here blocks traffic or takes "
    "automated action."
)

test, threshold = get_test_data()
model, features, explainer = get_model_and_explainer()
cascade_report = get_cascade_report()
stateless_metrics, loto_metrics = get_model_metrics()
shap_global = get_shap_global()
threshold_record = get_threshold_record()

# Operating-point strings, all derived from artifacts -- never hardcoded (the report and the
# product previously disagreed because these were literals; see TECHNICAL_REPORT.md section 7).
OP_VAL_FPR_PCT = threshold_record["achieved_val_thr_fpr"] * 100.0
OP_TEST_FPR_PCT = stateless_metrics["combined"]["fpr"] * 100.0
OP_LABEL = f"FPR={OP_TEST_FPR_PCT:.2f}% (test)"

tab_case, tab_evidence, tab_model = st.tabs(["Case Queue", "Session Evidence", "Model Card"])

# ---------------------------------------------------------------------------
with tab_case:
    st.subheader("Query-level triage queue")
    st.caption("Rows sorted by risk score, descending — analysts triage from the top.")

    # Precision-at-depth: the operational payoff of ranking, and its boundary. Both read from
    # results/metrics/ranking_quality_v1.json -- the head figure is never shown without the decay.
    rq = get_ranking_quality()
    if rq:
        depths = {r["cum_n"]: r for r in rq["precision_at_depth_tie_respecting"]}
        head = min(depths.values(), key=lambda r: r["cum_n"])
        flat_pct = rq["asymptotic_flat_precision"] * 100.0
        decay_n = rq["ranking_effective_until_depth"]
        st.info(
            f"**Top {head['cum_n']} alerts: {head['cum_precision']*100:.1f}% precision "
            f"({head['lift_over_base_rate']:.2f}× lift over the {rq['test_base_rate']*100:.1f}% "
            f"base rate).** Ranking advantage decays to base rate by depth ~{decay_n:,} "
            f"({flat_pct:.1f}%) — beyond that the score provides fixed enrichment, not "
            f"prioritisation. Triage the head of this queue, not its tail."
        )

    n_show = st.slider("Rows to show", 10, 200, 30, step=10)
    category_filter = st.multiselect(
        "Filter by attack_category", ["benign", "light", "heavy"], default=["benign", "light", "heavy"]
    )
    view = test[test["attack_category"].isin(category_filter)].sort_values("raw_score", ascending=False).head(n_show)

    display_cols = ["unit_id", "session_id", "attack_category", "raw_score"]
    st.dataframe(
        view[display_cols].assign(
            decision=view["raw_score"].apply(lambda s: decision_band(s, threshold)[0])
        ),
        use_container_width=True,
        hide_index=True,
    )

    st.divider()
    st.subheader("Inspect one query")
    selected_unit = st.selectbox("unit_id", view["unit_id"].tolist())
    row = test[test["unit_id"] == selected_unit].iloc[0]

    band, color = decision_band(row["raw_score"], threshold)
    col1, col2, col3 = st.columns(3)
    col1.metric("Risk score (raw)", f"{row['raw_score']:.4f}")
    col2.metric("Decision band", band)
    col3.metric("Ground truth (eval only)", "attack" if row["label"] == 1 else "benign")
    st.markdown(f"<div style='padding:8px;border-radius:6px;background:{color}22;border:1px solid {color}'>"
                f"<b style='color:{color}'>{band}</b> — alert threshold {threshold:.6f} "
                f"(selected on val_thr at {OP_VAL_FPR_PCT:.2f}% FPR; achieves "
                f"{OP_TEST_FPR_PCT:.2f}% FPR on test)</div>",
                unsafe_allow_html=True)

    st.markdown("**Top reason codes (SHAP, this query only):**")
    explanation = local_explanation(explainer, row, features, top_k=5)
    exp_df = pd.DataFrame(explanation)
    exp_df["shap_value"] = exp_df["shap_value"].round(4)
    exp_df["value"] = exp_df["value"].round(3)
    st.dataframe(exp_df, use_container_width=True, hide_index=True)
    st.caption(
        "Reason codes are exact SHAP contributions from the trained model on this row's own "
        "numeric features — no query text or domain identity is used or displayed (none exists "
        "in this schema; see configs/leakage_exclusions.yaml)."
    )

    session_verdicts = cascade_report.get("session_verdicts", {})
    verdict = session_verdicts.get(row["base_trace"])
    st.divider()
    st.subheader("Session-level status (Stage 2 cascade)")
    if verdict is None:
        st.info("No cascade verdict available for this session in the current test run.")
    elif not verdict.get("escalated"):
        computed_state = "not_escalated"
    elif not verdict.get("stateful_context_available", True):
        computed_state = "escalated_context_unavailable_fallback_stage1"
    elif verdict.get("confirmed"):
        computed_state = "escalated_confirmed_alert"
    else:
        computed_state = "escalated_unconfirmed_human_review"

    if verdict is not None:
        label, vcolor = verdict_badge(computed_state)
        st.markdown(f"<div style='padding:8px;border-radius:6px;background:{vcolor}22;border:1px solid {vcolor}'>"
                    f"<b style='color:{vcolor}'>{label}</b></div>", unsafe_allow_html=True)

    st.divider()
    st.subheader("Analyst disposition (advisory only — no automated action taken)")
    disp_col1, disp_col2, disp_col3 = st.columns(3)
    if disp_col1.button("Approve alert", key=f"approve_{selected_unit}"):
        st.success("Marked as approved for escalation to security team (recorded in session state only).")
    if disp_col2.button("Dismiss as false positive", key=f"dismiss_{selected_unit}"):
        st.warning("Marked as dismissed (recorded in session state only).")
    if disp_col3.button("Escalate to senior analyst", key=f"escalate_{selected_unit}"):
        st.info("Flagged for senior review (recorded in session state only).")
    st.caption(
        "These buttons record a disposition in this UI session only. No DNS blocking, host "
        "quarantine, or firewall change is triggered by this tool, per the project's safety "
        "constraint: detection is advisory, human approval required for any response."
    )

# ---------------------------------------------------------------------------
with tab_evidence:
    st.subheader("Session evidence: stateful context vs. train-set benign/attack baselines")
    st.caption(
        "Only escalated sessions reach Stage 2. These are the 3 discriminative stateful "
        "features chosen on TRAIN data only (never val/test) — see docs/PHASE2_PLAN.md item 7."
    )

    disc_features = cascade_report.get("discriminative_stateful_features", [])
    st.dataframe(pd.DataFrame(disc_features), use_container_width=True, hide_index=True)

    st.divider()
    session_verdicts = cascade_report.get("session_verdicts", {})
    for token, verdict in session_verdicts.items():
        with st.expander(f"Session: {token}  —  escalated={verdict.get('escalated', False)}"):
            if not verdict.get("escalated"):
                st.write("Not escalated — Stage 1 verdict stands for every row in this session.")
                continue
            if not verdict.get("stateful_context_available", True):
                st.write("Escalated, but stateful context unavailable for this capture — "
                         "graceful fallback to Stage 1 verdict, flagged for human review.")
                continue
            st.write(f"Stage 2 vote: {verdict.get('votes_attack_like')}/{verdict.get('votes_total')} "
                     f"features attack-like -> confirmed={verdict.get('confirmed')}")
            detail = verdict.get("detail", [])
            if detail:
                st.dataframe(pd.DataFrame(detail), use_container_width=True, hide_index=True)
            else:
                st.caption("Per-feature comparison unavailable — rerun `python -m src.models.cascade` "
                           "to regenerate the report with full detail.")

# ---------------------------------------------------------------------------
with tab_model:
    st.subheader("Model card — Stage 1 stateless detector")
    m1, m2, m3, m4 = st.columns(4)
    m1.metric("PR-AUC", f"{stateless_metrics['headline_pr_auc']:.4f}")
    m2.metric(f"Recall @ {OP_LABEL}", f"{stateless_metrics['combined']['recall']*100:.2f}%")
    m3.metric("Precision", f"{stateless_metrics['combined']['precision']*100:.2f}%")
    m4.metric("False alerts / 10k benign", f"{stateless_metrics['combined']['false_alerts_per_10k_benign']:.2f}")
    st.caption(
        f"Operating point: threshold {threshold_record['threshold']:.6f}, selected on "
        f"{threshold_record['selected_on']} at {OP_VAL_FPR_PCT:.2f}% FPR. "
        f"{threshold_record['selection_rule']}"
    )

    st.markdown("**Leave-one-day-out robustness** (fresh model per held-out calendar day):")
    loto_rows = [
        {"held_out_day": f["held_out_day"], "pr_auc": f.get("pr_auc_on_held_out_day"),
         "recall": f["point_metrics_on_held_out_day"]["recall"]}
        for f in loto_metrics["folds"]
    ]
    st.dataframe(pd.DataFrame(loto_rows), use_container_width=True, hide_index=True)
    st.caption(
        f"Mean PR-AUC {loto_metrics['fold_to_fold_variation']['pr_auc_mean']:.4f} "
        f"(std {loto_metrics['fold_to_fold_variation']['pr_auc_std']:.4f}) across "
        f"{loto_metrics['fold_to_fold_variation']['pr_auc_folds_used']} testable days."
    )

    st.divider()
    st.markdown("**Global feature importance (mean |SHAP|, sample of test rows)**")
    if shap_global:
        shap_df = pd.DataFrame(shap_global["ranked_features"])
        st.bar_chart(shap_df.set_index("feature")["mean_abs_shap"])
        st.caption(
            "sl_longest_word_len and sl_fqdn_count dominate -- consistent with the rule "
            "baseline (§6): attack queries in this dataset tend to be longer, and the model's "
            f"row-level recall reaches {stateless_metrics['combined']['recall']*100:.2f}% at "
            f"{OP_TEST_FPR_PCT:.2f}% FPR (§7) because length alone is a weak signal on its own. "
            "See report/TECHNICAL_REPORT.md §9 for why a much stronger "
            "session-derived feature was tried and rejected."
        )
    else:
        st.info("Run `python -m src.explain.shap_explain` to generate the global summary artifact.")

    st.divider()
    st.markdown("**Cascade (Track 2, two-stage) vs. Stage 1 alone**")
    one_stage = cascade_report.get("one_stage_stage1_only", {})
    two_stage = cascade_report.get("two_stage_cascade", {})
    comp_df = pd.DataFrame([
        {"design": "Stage 1 only", **one_stage},
        {"design": "Two-stage cascade", **two_stage},
    ])
    st.dataframe(comp_df, use_container_width=True, hide_index=True)
    st.caption(
        f"{cascade_report.get('pct_test_rows_escalated_to_stage2', 0)*100:.1f}% of test rows "
        f"escalated to the expensive Stage 2 path."
    )
